#!/bin/sh

declare svcplan="$(mktemp)"
trap "rm -f $svcplan" EXIT

export MSYS_NO_PATHCONV=1

# From
# https://learn.microsoft.com/en-us/cli/azure/azure-cli-sp-tutorial-1?tabs=bash
let "randomIdentifier=$RANDOM*$RANDOM"
servicePrincipalName="opentofu-$randomIdentifier"
subscriptionID=$(az account show --query id --output tsv)
# Verify the ID of the active subscription
echo "Using subscription ID $subscriptionID"
resourceGroup="app_sndbx"

echo "Creating SP for RBAC with name $servicePrincipalName, with role $roleName and in scopes /subscriptions/$subscriptionID/resourceGroups/$resourceGroup"
az ad sp create-for-rbac --name $servicePrincipalName \
                         --role "Owner" \
                         --scopes "/subscriptions/$subscriptionID/resourceGroups/$resourceGroup" > "$svcplan"

ARM_CLIENT_ID="$(jp --unquoted 'appId'  < $svcplan)"

# needed in order to run "tofu plan"
az role assignment create --assignee "$ARM_CLIENT_ID" --role "Reader"
# needed in order to run "tofu apply"
az role assignment create --assignee "$ARM_CLIENT_ID" --role "Owner"

echo ARM_SUBSCRIPTION_ID="\"$subscriptionID\""
echo ARM_TENANT_ID="\"$(jp --unquoted 'tenant' < $svcplan)\""
echo ARM_CLIENT_ID="\"${ARM_CLIENT_ID}\""
echo ARM_CLIENT_SECRET="\"$(jp --unquoted 'password' < $svcplan)\""
echo export ARM_SUBSCRIPTION_ID ARM_TENANT_ID ARM_CLIENT_ID ARM_CLIENT_SECRET
