#!/bin/sh

# Creates Service Principal delegate to run OpenTofu
# provisioning
# October 13, 2023
# Allan Peda <allan.peda@interpublic.com>

set -eEuo pipefail
## Constants
################################
declare -r COMMON_PREFIX='opentofu'
# Reader role is needed for creating the plan
# Contributor role is needed for applying the plan
declare -a SPROLES=('Contributor' 'Reader')

svcplan="$(mktemp)"
# shellcheck disable=SC2064
trap "rm -f $svcplan" EXIT

# From
# https://learn.microsoft.com/en-us/cli/azure/azure-cli-sp-tutorial-1?tabs=bash
let "randomIdentifier=$RANDOM*$RANDOM"
servicePrincipalName="${COMMON_PREFIX}-$randomIdentifier"
subscriptionID=$(az account show --query id --output tsv)
# Verify the ID of the active subscription
echo "Using subscription ID: $subscriptionID" >&2
resourceGroup="${COMMON_PREFIX}-rg"
if [[ $(az group exists --name "$resourceGroup") == true ]]
then
   echo "Using Resource Group:  $resourceGroup" >&2
else
   echo "Please create Resource Group:  $resourceGroup" >&2
   exit 1
fi

echo -n "Creating SP for RBAC with name $servicePrincipalName, " >&2
echo "with role ${SPROLES[0]} and in scopes /subscriptions/$subscriptionID/resourceGroups/$resourceGroup" >&2
az ad sp create-for-rbac --name $servicePrincipalName \
                         --role "${SPROLES[0]}" \
                         --scopes "/subscriptions/$subscriptionID/resourceGroups/$resourceGroup" > "$svcplan"

ARM_CLIENT_ID="$(jp --unquoted 'appId'  < "$svcplan")"

# not sure why I had to do assign roles explicitly
for r in "${SPROLES[@]}"
do
   az role assignment create --assignee "$ARM_CLIENT_ID" --role "$r" > /dev/null
done

echo ARM_SUBSCRIPTION_ID="\"$subscriptionID\""
echo ARM_TENANT_ID="\"$(jp --unquoted 'tenant' < "$svcplan")\""
echo ARM_CLIENT_ID="\"${ARM_CLIENT_ID}\""
echo ARM_CLIENT_SECRET="\"$(jp --unquoted 'password' < "$svcplan")\""
echo export ARM_SUBSCRIPTION_ID ARM_TENANT_ID ARM_CLIENT_ID ARM_CLIENT_SECRET
